### PR TITLE
Fix #52 by setting group roster sharing to false by default

### LINKED ISSUE #52: Should not create groups as 'shared'
When a new group gets created through the existing REST API implementation, it is created as a 'shared group'. This is undesirable.

This line in the code creates the group as a 'shared' (rather than a non-shared) group:

https://github.com/igniterealtime/openfire-restAPI-plugin/blob/a49d0e2161fc3f39016e924c520dc382a171001a/src/java/org/jivesoftware/openfire/plugin/rest/controller/GroupController.java#L93

Shared groups can have significant performance overhead: whenever rosters from a group member are obtained, these are supplemented with items referencing all other members of the group.

The use-case for applying the REST API plugin is often one of automation, which makes it likely that the environment where it is applied is one of high volume.

The API should be modified to create a group as a shared group only when explicitly configured to be so.

### PR DESCRIPTION
**Pull request by Fishbowler**
Roster sharing is an optional parameter of creating/updating a group, but when not provided is assumed to be false.

Could be a breaking change for some users.

### CODE REVIEW

**Comment by Fishbowler** [comment]
Rebased to fix conflicts in the changelog

**Comment by Fishbowler** [comment]
Rebased.

I've also moved the default of false to the Entity. 
Since it's not a required field, in the initial implementation it would be set to false by default on creation and unchanged on update. This amends the implementation to always defaulting the field to false when not supplied.

**Comment by Fishbowler** [comment]
...and added some annotations on the Entity to give better examples in the Swagger.

Let me know if this is an overreach for this PR, and I'll move them into a separate branch.

**Comment by guusdk** [comment]
I don't think we need to bother by putting those in distinct branches. Thanks Dan!

**Pull request merged**
