### PR TITLE
fix cors issue

### PR DESCRIPTION
**Pull request by supun19**
fix the cors issue

### CODE REVIEW

**Comment by mudrila** [comment]
Can we get it merged?

**Comment by Redor** [comment]
There is a problem with multiple filters (cors, auth, gzip). They don't work properly together. 
By enabling CORS, GZIP does not work (or auth)

**Comment by mudrila** [comment]
So, what is way to get CORS enabled? For me - this plugin doesn't work at all, cause any requests I do from browser are failed 😞 (because of "No Access Control Allow Origin blah blah blah)

**Comment by Redor** [comment]
Currently they isn't a good solution for that issue. (Except to investigate further to that issue and try to fix it. Or rewrite the code (from jersey to something else, or newer version). 
Maybe you can execute your requests not from a Browser?

**Comment by deleolajide** [comment]
I had the same problem with the chat api plugin based on this plugin. For now, [gzip is disabled and only cors is enabled](https://github.com/igniterealtime/Openfire-Chat/blob/9259bdb6a65fc5f53edbbc6873684787fe3a2fc5/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java#L148).

**Comment by Redor** [comment]
That issue is fixed in https://github.com/igniterealtime/openfire-restAPI-plugin/releases/tag/1.3.10

**Pull request closed without merging**
