### PR TITLE
Fix #76: Add clustering status endpoint

### LINKED ISSUE #76: Add endpoint for clustering information
Add an additional endpoint for an administrator to return the clustering status of a given Openfire instance

### PR DESCRIPTION
**Pull request by Fishbowler**
Add endpoint to return simple string indicating clustering status of Openfire

### CODE REVIEW

**Comment by Fishbowler** [comment]
🤦‍♂️ Needs changelog

**Comment by Fishbowler** [comment]
🤦‍♂️ Needs API docs too

**Comment by Fishbowler** [comment]
Fixed the missing bits, and rebased.

**Comment by guusdk** [comment]
I suggest to re-order things a bit:

- Have the endpoint be named: `restapi/v1/cluster`
- Have the entity be named: `clusternode`
- Have the entity include not only the status, but also the name/ID of the node

That way, you can GET `restapi/v1/cluster` to obtain an overview of all cluster nodes that are in the cluster (with their current state and name. GETting `restapi/v1/cluster/<id>` could be used to query just one of them.

**Comment by guusdk** [comment]
Rebased to current HEAD of the master branch.

**Comment by guusdk** [comment]
I have rebased again, and added two new endpoints. @Fishbowler can you please review these changes? I'm happy to merge this if you are.

**Review by guusdk — APPROVED** [review]

**Comment by Fishbowler** [comment]
Those are awesome additions. Fixed one readability thing (mine) and one copy pasta (yours). LGTM :+1:

**Pull request merged**
