### PR TITLE
Add licensing information (#72)

### LINKED ISSUE #72: Add license information
It's hard to determine what license this plugin is distributed under. We should add references to the Apache2 license in:

- the pom.xml file
- the source code files
- the github repo (which probably picks up a LICENSE file in the root of the directory
- ... ?

### PR DESCRIPTION
**Pull request by Fishbowler**
Fixes #72 by adding license information everywhere where @guusdk suggested

### CODE REVIEW

**Comment by Fishbowler** [comment]
There were some old Ignite copyright licenses on a couple of files, so I've left them.
I've not bothered to use git history to find the original dates for the files, and set them all to 2022.
Assume there's no objection to either of these things?

**Comment by guusdk** [comment]
Ah, thanks for doing this Dan. I don't speak legaleeze, but shouldn't copyright by claimed by some kind of entity. Just saying

> Copyright (c) 2022.

doesn't inform who claims copyright.

Would this be more appropriate?

> Copyright (c) 2022 Ignite Realtime Foundation.

(or @Redor's full name, if he prefers that).

**Comment by GregDThomas** [comment]
My 2p;

I can only speak from my own experience, but .advice I've been given by expensive corporate lawyers in the past is that, in the UK at least (paraphrasing), copyright is automatic and you don't need to assert anything for it to apply. Though the (c) Date Owner thing is useful for records, for OSS this sort of thing is held in GitHub anyway so of little benefit, and as a result  none of the code in https://github.com/BT-OpenSource (for example) has an explicit copyright statement.

**Comment by guusdk** [comment]
Ah, that's interesting. I wonder if that holds true outside of the UK realm - but then again, we're probably breaking some rules somewhere anyway. The primary benefit of having the header for me would be to denote the license anyway, not to assert copyright.

**Comment by Fishbowler** [comment]
Rebased.

**Pull request merged**
