### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by Redor** [comment]
Looks good for me @guusdk 
Thy

**Comment by guusdk** [comment]
Ugh - you squashed, which means that the single commit that defined the version as '1.6.0' now is no longer available.

**Comment by guusdk** [comment]
I'm going to do ugly things with force-pushing to master to rectify :)

**Comment by Redor** [comment]
Sry :)

**Comment by guusdk** [comment]
No worries. Should be fine with this one now: https://github.com/igniterealtime/openfire-restAPI-plugin/pull/60

**Pull request merged**
